Repository raveljs/ravel, pull requests merged in 2018-04, with the labels that each got.

#229 Bumping core module versions for bugfixes and enhancements.
  package.json
  test/core/test-params.js
Labels: dependencies, semver-minor

#231 Some README links are broken [skip ci]
  README.md
Labels: bug, documentation

#233 Adding in-memory redis default, rather than requiring external redis.
  README.md
  lib/ravel.js
  lib/util/kvstore.js
  package.json
  test/auth/test-passport-init.js
  test/core/decorators/test-middleware.js
  test/core/test-params.js
  test/core/test-reflect.js
  test/core/test-resource.js
  test/core/test-routes.js
  test/ravel/test-ravel-middleware.js
  test/ravel/test-ravel.js
Labels: documentation, feature, semver-minor

#235 Fix for #234 - local kvstore issue
  lib/util/kvstore.js
  package.json
Labels: bug, semver-patch

#238 Allow Environment Variables to be used in .ravelrc.json
  README.md
  lib/core/params.js
  package.json
  test/core/test-params.js
Labels: feature, semver-minor
