Repository raveljs/ravel, pull requests merged in 2020-10, with the labels that each got.

#305 No longer recommending the use of node-pool [skip-ci]
  lib/db/database_provider.js
Labels: documentation, semver-patch

#306 Adding HEAD functionality to Routes and Resource, and PATCH to Resource.
  README.md
  jest/core/reflect.test.js
  jest/core/resource.test.js
  jest/core/routes.test.js
  jest/util/route-tree.test.js
  lib/core/decorators/mapping.js
  lib/core/decorators/resource.js
  lib/core/resource.js
  lib/core/router.js
  lib/core/routes.js
  lib/util/rest.js
  lib/util/route-tree.js
Labels: feature, semver-minor

#307 Feature/dependency update
  .travis.yml
  jest/integration/ravel-caching.test.js
  jest/util/rest.test.js
  lib/core/scan.js
  lib/util/meta.js
  lib/util/response_cache.js
  lib/util/rest.js
  lib/util/route-tree.js
  package-lock.json
  package.json
Labels: dependencies, semver-patch

#308 Forgot to bump appveyor node version
  .appveyor.yml
Labels: devops, semver-patch, tests

#304 Ensure samesite can be set on downstream applications
  README.md
  jest/core/params.test.js
  lib/ravel.js
Labels: documentation, feature, semver-minor, tests

#309 Bumping version for release. Fixing typos
  CONTRIBUTING.md
  README.md
  documentation.yml
  package-lock.json
  package.json
Labels: dependencies, documentation, feature, semver-minor, tests

#310 Switching master to main
  CONTRIBUTING.md
  README.md
Labels: documentation
